### ISSUE TITLE
[Meta] Changes for v0.3 - add_flat() and rename parameters

### ISSUE THREAD

**Issue by statnmap** [ThinkR-open/fusen#73]
These modifications will deprecate some existing use. We will try to make it as smooth as possible.  

Issues and PR related to this list, will be merged in the branch named `v0.3` until documentation and tests are fully operational.

## `add_flat_template()`

- [x] This superseeds `add_dev_history()`. We keep `add_dev_history()` as is but it will call `add_flat_template()` and show a superseeding message saying that the use will be clearer (as for gather / pivot_longer).

Like ?
```r
  if( !is.null(name) ){
    warning("The `name` argument to `add_dev_history()` is deprecated since {fusen} version xyz, and will be removed in a future version.\nPlease use `template` instead.\n")
    template <- name
  }     
```
### Parameters - similar to `add_dev_history()`

- `pkg = "."`,
-  `overwrite = FALSE`,
-  `open = TRUE`,
-  `dev_dir = "dev"`,
-  `template = c("full", "minimal", "additional", "teaching", "dev_history", "function")` - Previously `name` (issue https://github.com/ThinkR-open/fusen/issues/48)
- [x]  `flat_name = paste("flat_", template_name[1])` " - except for dev_history

### Available templates

> Follow-up of issue https://github.com/ThinkR-open/fusen/issues/46  

- [x] **teaching**: This keeps being a single flat file with the `description` chunk and already filed functions. Everything in the same place to present the structure of a package is a good first step
- [x] **full** - 2 files added - the default also in `create_fusen()`
    - A "dev_history.Rmd" template with `description` chunk and `development` chunk with good {usethis} (readme, news, pkgdown, ci), {attachment}, {pkgdown}, {gitlabr} CI tools listed.
    - A "flat_full.Rmd" template with already filled examples for `dev` with "data", `function`, `examples` and `tests` - Same as today "full", but without `description`
- [x] **minimal** - 2 files added (issue https://github.com/ThinkR-open/fusen/issues/44)
    - A "dev_history.Rmd" template as full
    - A "flat_minimal.Rmd" with empty chunks - Same as "minimal" today, without `description`
- [x] **additional** - 1 file added 
    - A "flat_additional.Rmd" with empty chunks - Same as "minimal" today, without `description` 
    - This supposes that it is used to add one new function named `filename` similarly to `build_fusen_chunks()` (issue https://github.com/ThinkR-open/fusen/issues/49)
      - chunk names are named with this filename
      - A function skeleton is already added with roxygen (issue https://github.com/ThinkR-open/fusen/issues/54)
- [x] **dev_history** - 1 file added
    - A "dev_history.Rmd" template as full 
- [ ] A path to a user template (https://github.com/ThinkR-open/fusen/issues/61)
    - Adds the template of the use with file.copy() 
    - This requires to check for path, before using `match.arg()`

## `inflate()` and Vignette

- [ ] Add tag  `<!-- flat:flatname - begin -->` and `<!-- flat:flatname - end -->` to encapsulate code in a vignette that comes from a specific flat file: https://github.com/ThinkR-open/fusen/issues/111
- [x]  `vignette_name` superseeds `name` for vignette name 
    - A message will inform users of `name` that it will be deprecated in a future version of {fusen} 
    - If `vignette_name=NULL` or `""` or `NA", then no vignette is built. (issue https://github.com/ThinkR-open/fusen/issues/50)
    - If `vignette_name` is an existing vignette, then, add after the last tag `<!-- flat:flatname - end -->` or update within the tag corresponding to the flatname.

## Others

- [x] Use devtools:check() instead of {rcmdcheck}: https://github.com/ThinkR-open/fusen/issues/82 . 
- [x] Pre-filled dev_history for one function: https://github.com/ThinkR-open/fusen/issues/49
- [x] Multiple functions in same R / test file: https://github.com/ThinkR-open/fusen/issues/57 
- [x] Vignette with tips and tricks:  https://github.com/ThinkR-open/fusen/issues/84

## Do not forget unit tests and documentation associated with these changes

- [x] Readme informs of the new use
- [x] Both Vignettes too
- [x] Unit tests accounts for deprecation messages with first use of the function

**Comment by statnmap** [comment]
Added in https://github.com/ThinkR-open/fusen/releases/tag/v0.3.0
